version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "data/**",
  "node_modules/"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"
enabled = true
