# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        language_version: '3.8'

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/PyCQA/isort
    rev: '5.11.5'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort

#-   repo: https://github.com/pre-commit/mirrors-pylint
#    rev: ''  # Use the sha / tag you want to point at
#    hooks:
#    -   id: pylint

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: rst-backticks
    -   id: rst-inline-touching-normal

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
    -   id: shellcheck

# -   repo: https://github.com/gruntwork-io/pre-commit
#     rev: 'v0.1.17'
#     hooks:
#     -   id: markdown-link-check

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade

# -   repo: https://github.com/ibm/detect-secrets
#     rev: 0.13.1+ibm.47.dss
#     hooks:
#     -   id: detect-secrets
#         name: Detect secrets (IBM)
#         language: python
#         entry: detect-secrets
#         args: ['scan', '--update', '.secrets.baseline', '--use-all-plugins']

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--verbose,  -r, ssacc, -c, .bandit.yaml]

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
