# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: ''  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort

#-   repo: https://github.com/pre-commit/mirrors-pylint
#    rev: ''  # Use the sha / tag you want to point at
#    hooks:
#    -   id: pylint

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0  # Use the ref you want to point at
    hooks:
    -   id: rst-backticks
    -   id: rst-inline-touching-normal

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: ''
    hooks:
    -   id: shellcheck

# -   repo: https://github.com/gruntwork-io/pre-commit
#     rev: ''
#     hooks:
#     -   id: markdown-link-check
