# .github/workflows/detect-secrets.yaml
name: detect-secrets

on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # tag=v1.4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      with:
        fetch-depth: 0

    - name: Run IBM's detect-secrets
      uses: sett-and-hive/detect-secrets-action@5358d1f7c812225e42dc7b235c512e07a7ec58e4 # tag=v2.1.1

    # - name: Commit back .secrets.baseline (if it was missing)
    #   uses: git-auto-commit-action@master
    #   with:
    #     commit_message: "build(detect-secrets): Commit the newly-generated .secrets.baseline file"
