# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull-request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run IBM's detect-secrets
      uses: tomwillis608/detect-secrets-action@master

    # - name: Commit back .secrets.baseline (if it was missing)
    #   uses: git-auto-commit-action@master
    #   with:
    #     commit_message: "build(detect-secrets): Commit the newly-generated .secrets.baseline file"
