# .github/workflows/ci.yaml
name: pre-commit CI in Docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:


    name: "Pre-commit tests in Docker"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        clean: true

    - name: Get Time Start
      id: start_time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Run pre-commit in a container
      uses: tomwillis608/docker-pre-commit-terraform@master

    - name: Get Time End
      id: end_time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'YYYY-MM-DD-HH-mm-ss'
