# .github/workflows/ci.yaml
name: pre-commit CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: "Pre-commit tests"
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # tag=v1.4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Checkout"
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      with:
        clean: true

    - name: "Set up Python"
      uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4
      with:
        python-version: "3.8"

    - name: "Install dependencies"
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade pre-commit
        pre-commit install

    - name: "Run pre-commit"
      run: "pre-commit run --all-files"
