# .github/workflows/pycharm_security.yaml
name: pycharm_security

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run PyCharm Security # Does SCA with SafetyDB
        uses: tonybaloney/pycharm-security@5c1ceeb1fb2a18478fa7076a81f9f47fd450e592 # tag=v1.25
        with:
          path: ssacc/
