# .github/workflows/pycharm_security.yaml
name: pycharm_security

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Run PyCharm Security # Does SCA with SafetyDB
        uses: tonybaloney/pycharm-security@fe5cb0f19b866ff109f1402a88ab9385da972fd3 # tag=v1.25
        with:
          path: ssacc/
