# .github/workflows/pycharm_security.yaml
name: pycharm_security

on: [push]

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v1
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
    with:
      - uses: ssacc/
