# .github/workflows/pycharm_security.yaml
name: pycharm_security

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Run PyCharm Security # Does SCA with SafetyDB
        uses: tonybaloney/pycharm-security@8a6e367ebf3b068f8b7b5f3414f049a70c50e2ab # tag=v1.25
        with:
          path: ssacc/
