# .github/workflows/pycharm_security.yaml
name: pycharm_security

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v3
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
        with:
          path: ssacc/
