# .github/workflows/ci.yaml
name: Nox-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.10'
    strategy:
      matrix:
        python-version: ["3.8", "3.9","3.10"]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 #  tag=v1.4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Checkout"
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      with:
        clean: true

    - name: "Set up Python"
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: "${{ matrix.python-version }}"
        architecture: x64

    - run: pip install nox==2022.8.7
    - run: pip install poetry==1.2.0
    - run: pip install nox-poetry==1.0.1

    - run: nox -p ${{ matrix.python-version }}

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: false
