# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - '**.md'

jobs:
  test:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        clean: true

    - name: "Set up Python"
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Install dependencies"
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
        # python -m pip install --upgrade cmake
        # python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions codecov randomly
        python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions codecov

    - name: "Run tox targets for ${{ matrix.python-version }}"
      run: "python -m tox"

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v2
      with:
        verbose: true
        fail_ci_if_error: true
