# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        verbose: true

    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python-version }}"
        verbose: true

    - name: "Install dependencies"
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions codecov randomly

    - name: "Run tox targets for ${{ matrix.python-version }}"
      run: "python -m tox"
      with:
        verbose: true

    - name: "Post to codecov.io"
      uses: codecov/codecov-action@v1
      with:
        verbose: true
